application: skillshelves
version: 1
runtime: python
api_version: 1

handlers:
- url: /favicon.ico
  static_files: images/favicon.ico
  upload: images/favicon.ico
- url: /static
  static_dir: static
- url: /images
  static_dir: images
- url: /administrativa/.*
  script: admin.py
  login: admin
- url: /json/.*
  script: json.py
#- url: /_ah/login_required
#  script: main.py
#- url: /_ah/login
#  script: main.py
- url: /.*
  script: main.py